# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: token/prover.proto for package 'protos'
# Original file comments:
#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

require 'grpc'
require 'token/prover_pb'

module Protos
  module Prover
    # Prover provides support to clients for the creation of FabToken transactions,
    # and to query the ledger.
    class Service
      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'protos.Prover'

      # ProcessCommand processes the passed command ensuring proper access control.
      # The returned response allows the client to understand if the
      # operation was succeffully executed and if not, the response
      # reports the reason of the failure.
      rpc :ProcessCommand, SignedCommand, SignedCommandResponse
    end

    Stub = Service.rpc_stub_class
  end
end
