# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token/transaction.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message 'TokenTransaction' do
    oneof :action do
      optional :plain_action, :message, 1, 'PlainTokenAction'
    end
  end
  add_message 'PlainTokenAction' do
    oneof :data do
      optional :plain_import, :message, 1, 'PlainImport'
      optional :plain_transfer, :message, 2, 'PlainTransfer'
    end
  end
  add_message 'PlainImport' do
    repeated :outputs, :message, 1, 'PlainOutput'
  end
  add_message 'PlainTransfer' do
    repeated :inputs, :message, 1, 'InputId'
    repeated :outputs, :message, 2, 'PlainOutput'
  end
  add_message 'PlainOutput' do
    optional :owner, :bytes, 1
    optional :type, :string, 2
    optional :quantity, :uint64, 3
  end
  add_message 'InputId' do
    optional :tx_id, :bytes, 1
    optional :index, :uint32, 2
  end
end

TokenTransaction = Google::Protobuf::DescriptorPool.generated_pool.lookup('TokenTransaction').msgclass
PlainTokenAction = Google::Protobuf::DescriptorPool.generated_pool.lookup('PlainTokenAction').msgclass
PlainImport = Google::Protobuf::DescriptorPool.generated_pool.lookup('PlainImport').msgclass
PlainTransfer = Google::Protobuf::DescriptorPool.generated_pool.lookup('PlainTransfer').msgclass
PlainOutput = Google::Protobuf::DescriptorPool.generated_pool.lookup('PlainOutput').msgclass
InputId = Google::Protobuf::DescriptorPool.generated_pool.lookup('InputId').msgclass
