# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/collection.proto

require 'google/protobuf'

require 'common/policies_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message 'common.CollectionConfigPackage' do
    repeated :config, :message, 1, 'common.CollectionConfig'
  end
  add_message 'common.CollectionConfig' do
    oneof :payload do
      optional :static_collection_config, :message, 1, 'common.StaticCollectionConfig'
    end
  end
  add_message 'common.StaticCollectionConfig' do
    optional :name, :string, 1
    optional :member_orgs_policy, :message, 2, 'common.CollectionPolicyConfig'
    optional :required_peer_count, :int32, 3
    optional :maximum_peer_count, :int32, 4
    optional :block_to_live, :uint64, 5
  end
  add_message 'common.CollectionPolicyConfig' do
    oneof :payload do
      optional :signature_policy, :message, 1, 'common.SignaturePolicyEnvelope'
    end
  end
  add_message 'common.CollectionCriteria' do
    optional :channel, :string, 1
    optional :tx_id, :string, 2
    optional :collection, :string, 3
    optional :namespace, :string, 4
  end
end

module Common
  CollectionConfigPackage = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.CollectionConfigPackage').msgclass
  CollectionConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.CollectionConfig').msgclass
  StaticCollectionConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.StaticCollectionConfig').msgclass
  CollectionPolicyConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.CollectionPolicyConfig').msgclass
  CollectionCriteria = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.CollectionCriteria').msgclass
end
