# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/configuration.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message 'common.HashingAlgorithm' do
    optional :name, :string, 1
  end
  add_message 'common.BlockDataHashingStructure' do
    optional :width, :uint32, 1
  end
  add_message 'common.OrdererAddresses' do
    repeated :addresses, :string, 1
  end
  add_message 'common.Consortium' do
    optional :name, :string, 1
  end
  add_message 'common.Capabilities' do
    map :capabilities, :string, :message, 1, 'common.Capability'
  end
  add_message 'common.Capability' do
  end
end

module Common
  HashingAlgorithm = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.HashingAlgorithm').msgclass
  BlockDataHashingStructure = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.BlockDataHashingStructure').msgclass
  OrdererAddresses = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.OrdererAddresses').msgclass
  Consortium = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.Consortium').msgclass
  Capabilities = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.Capabilities').msgclass
  Capability = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.Capability').msgclass
end
