# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/policies.proto

require 'google/protobuf'

require 'msp/msp_principal_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message 'common.Policy' do
    optional :type, :int32, 1
    optional :value, :bytes, 2
  end
  add_enum 'common.Policy.PolicyType' do
    value :UNKNOWN, 0
    value :SIGNATURE, 1
    value :MSP, 2
    value :IMPLICIT_META, 3
  end
  add_message 'common.SignaturePolicyEnvelope' do
    optional :version, :int32, 1
    optional :rule, :message, 2, 'common.SignaturePolicy'
    repeated :identities, :message, 3, 'common.MSPPrincipal'
  end
  add_message 'common.SignaturePolicy' do
    oneof :Type do
      optional :signed_by, :int32, 1
      optional :n_out_of, :message, 2, 'common.SignaturePolicy.NOutOf'
    end
  end
  add_message 'common.SignaturePolicy.NOutOf' do
    optional :n, :int32, 1
    repeated :rules, :message, 2, 'common.SignaturePolicy'
  end
  add_message 'common.ImplicitMetaPolicy' do
    optional :sub_policy, :string, 1
    optional :rule, :enum, 2, 'common.ImplicitMetaPolicy.Rule'
  end
  add_enum 'common.ImplicitMetaPolicy.Rule' do
    value :ANY, 0
    value :ALL, 1
    value :MAJORITY, 2
  end
end

module Common
  Policy = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.Policy').msgclass
  Policy::PolicyType = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.Policy.PolicyType').enummodule
  SignaturePolicyEnvelope = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.SignaturePolicyEnvelope').msgclass
  SignaturePolicy = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.SignaturePolicy').msgclass
  SignaturePolicy::NOutOf = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.SignaturePolicy.NOutOf').msgclass
  ImplicitMetaPolicy = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.ImplicitMetaPolicy').msgclass
  ImplicitMetaPolicy::Rule = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.ImplicitMetaPolicy.Rule').enummodule
end
