# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: discovery/protocol.proto for package 'discovery'
# Original file comments:
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

require 'grpc'
require 'discovery/protocol_pb'

module Discovery
  module Discovery
    # Discovery defines a service that serves information about the fabric network
    # like which peers, orderers, chaincodes, etc.
    class Service
      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'discovery.Discovery'

      # Discover receives a signed request, and returns a response.
      rpc :Discover, SignedRequest, Response
    end

    Stub = Service.rpc_stub_class
  end
end
