# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: orderer/cluster.proto for package 'orderer'
# Original file comments:
#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

require 'grpc'
require 'orderer/cluster_pb'

module Orderer
  module Cluster
    # Cluster defines communication between cluster members.
    class Service
      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'orderer.Cluster'

      # Submit submits transactions to a cluster member
      rpc :Submit, stream(SubmitRequest), stream(SubmitResponse)
      # Step passes an implementation-specific message to another cluster member.
      rpc :Step, StepRequest, StepResponse
    end

    Stub = Service.rpc_stub_class
  end
end
