# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderer/cluster.proto

require 'google/protobuf'

require 'common/common_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message 'orderer.StepRequest' do
    optional :channel, :string, 1
    optional :payload, :bytes, 2
  end
  add_message 'orderer.StepResponse' do
    optional :payload, :bytes, 1
  end
  add_message 'orderer.SubmitRequest' do
    optional :channel, :string, 1
    optional :last_validation_seq, :uint64, 2
    optional :content, :message, 3, 'common.Envelope'
  end
  add_message 'orderer.SubmitResponse' do
    optional :status, :enum, 1, 'common.Status'
    optional :info, :string, 2
  end
end

module Orderer
  StepRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup('orderer.StepRequest').msgclass
  StepResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup('orderer.StepResponse').msgclass
  SubmitRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup('orderer.SubmitRequest').msgclass
  SubmitResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup('orderer.SubmitResponse').msgclass
end
