# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderer/configuration.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message 'orderer.ConsensusType' do
    optional :type, :string, 1
    optional :metadata, :bytes, 2
  end
  add_message 'orderer.BatchSize' do
    optional :max_message_count, :uint32, 1
    optional :absolute_max_bytes, :uint32, 2
    optional :preferred_max_bytes, :uint32, 3
  end
  add_message 'orderer.BatchTimeout' do
    optional :timeout, :string, 1
  end
  add_message 'orderer.KafkaBrokers' do
    repeated :brokers, :string, 1
  end
  add_message 'orderer.ChannelRestrictions' do
    optional :max_count, :uint64, 1
  end
end

module Orderer
  ConsensusType = Google::Protobuf::DescriptorPool.generated_pool.lookup('orderer.ConsensusType').msgclass
  BatchSize = Google::Protobuf::DescriptorPool.generated_pool.lookup('orderer.BatchSize').msgclass
  BatchTimeout = Google::Protobuf::DescriptorPool.generated_pool.lookup('orderer.BatchTimeout').msgclass
  KafkaBrokers = Google::Protobuf::DescriptorPool.generated_pool.lookup('orderer.KafkaBrokers').msgclass
  ChannelRestrictions = Google::Protobuf::DescriptorPool.generated_pool.lookup('orderer.ChannelRestrictions').msgclass
end
