# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msp/msp_principal.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message 'common.MSPPrincipal' do
    optional :principal_classification, :enum, 1, 'common.MSPPrincipal.Classification'
    optional :principal, :bytes, 2
  end
  add_enum 'common.MSPPrincipal.Classification' do
    value :ROLE, 0
    value :ORGANIZATION_UNIT, 1
    value :IDENTITY, 2
    value :ANONYMITY, 3
    value :COMBINED, 4
  end
  add_message 'common.OrganizationUnit' do
    optional :msp_identifier, :string, 1
    optional :organizational_unit_identifier, :string, 2
    optional :certifiers_identifier, :bytes, 3
  end
  add_message 'common.MSPRole' do
    optional :msp_identifier, :string, 1
    optional :role, :enum, 2, 'common.MSPRole.MSPRoleType'
  end
  add_enum 'common.MSPRole.MSPRoleType' do
    value :MEMBER, 0
    value :ADMIN, 1
    value :CLIENT, 2
    value :PEER, 3
  end
  add_message 'common.MSPIdentityAnonymity' do
    optional :anonymity_type, :enum, 1, 'common.MSPIdentityAnonymity.MSPIdentityAnonymityType'
  end
  add_enum 'common.MSPIdentityAnonymity.MSPIdentityAnonymityType' do
    value :NOMINAL, 0
    value :ANONYMOUS, 1
  end
  add_message 'common.CombinedPrincipal' do
    repeated :principals, :message, 1, 'common.MSPPrincipal'
  end
end

module Common
  MSPPrincipal = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.MSPPrincipal').msgclass
  MSPPrincipal::Classification = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.MSPPrincipal.Classification').enummodule
  OrganizationUnit = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.OrganizationUnit').msgclass
  MSPRole = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.MSPRole').msgclass
  MSPRole::MSPRoleType = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.MSPRole.MSPRoleType').enummodule
  MSPIdentityAnonymity = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.MSPIdentityAnonymity').msgclass
  MSPIdentityAnonymity::MSPIdentityAnonymityType = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.MSPIdentityAnonymity.MSPIdentityAnonymityType').enummodule
  CombinedPrincipal = Google::Protobuf::DescriptorPool.generated_pool.lookup('common.CombinedPrincipal').msgclass
end
