# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/chaincode_event.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message 'protos.ChaincodeEvent' do
    optional :chaincode_id, :string, 1
    optional :tx_id, :string, 2
    optional :event_name, :string, 3
    optional :payload, :bytes, 4
  end
end

module Protos
  ChaincodeEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup('protos.ChaincodeEvent').msgclass
end
