# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/events.proto

require 'google/protobuf'

require 'common/common_pb'
require 'google/protobuf/timestamp_pb'
require 'peer/chaincode_event_pb'
require 'peer/transaction_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message 'protos.FilteredBlock' do
    optional :channel_id, :string, 1
    optional :number, :uint64, 2
    repeated :filtered_transactions, :message, 4, 'protos.FilteredTransaction'
  end
  add_message 'protos.FilteredTransaction' do
    optional :txid, :string, 1
    optional :type, :enum, 2, 'common.HeaderType'
    optional :tx_validation_code, :enum, 3, 'protos.TxValidationCode'
    oneof :Data do
      optional :transaction_actions, :message, 4, 'protos.FilteredTransactionActions'
    end
  end
  add_message 'protos.FilteredTransactionActions' do
    repeated :chaincode_actions, :message, 1, 'protos.FilteredChaincodeAction'
  end
  add_message 'protos.FilteredChaincodeAction' do
    optional :chaincode_event, :message, 1, 'protos.ChaincodeEvent'
  end
  add_message 'protos.DeliverResponse' do
    oneof :Type do
      optional :status, :enum, 1, 'common.Status'
      optional :block, :message, 2, 'common.Block'
      optional :filtered_block, :message, 3, 'protos.FilteredBlock'
    end
  end
end

module Protos
  FilteredBlock = Google::Protobuf::DescriptorPool.generated_pool.lookup('protos.FilteredBlock').msgclass
  FilteredTransaction = Google::Protobuf::DescriptorPool.generated_pool.lookup('protos.FilteredTransaction').msgclass
  FilteredTransactionActions = Google::Protobuf::DescriptorPool.generated_pool.lookup('protos.FilteredTransactionActions').msgclass
  FilteredChaincodeAction = Google::Protobuf::DescriptorPool.generated_pool.lookup('protos.FilteredChaincodeAction').msgclass
  DeliverResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup('protos.DeliverResponse').msgclass
end
