# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/proposal.proto

require 'google/protobuf'

require 'peer/chaincode_pb'
require 'peer/proposal_response_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message 'protos.SignedProposal' do
    optional :proposal_bytes, :bytes, 1
    optional :signature, :bytes, 2
  end
  add_message 'protos.Proposal' do
    optional :header, :bytes, 1
    optional :payload, :bytes, 2
    optional :extension, :bytes, 3
  end
  add_message 'protos.ChaincodeHeaderExtension' do
    optional :payload_visibility, :bytes, 1
    optional :chaincode_id, :message, 2, 'protos.ChaincodeID'
  end
  add_message 'protos.ChaincodeProposalPayload' do
    optional :input, :bytes, 1
    map :TransientMap, :string, :bytes, 2
  end
  add_message 'protos.ChaincodeAction' do
    optional :results, :bytes, 1
    optional :events, :bytes, 2
    optional :response, :message, 3, 'protos.Response'
    optional :chaincode_id, :message, 4, 'protos.ChaincodeID'
  end
end

module Protos
  SignedProposal = Google::Protobuf::DescriptorPool.generated_pool.lookup('protos.SignedProposal').msgclass
  Proposal = Google::Protobuf::DescriptorPool.generated_pool.lookup('protos.Proposal').msgclass
  ChaincodeHeaderExtension = Google::Protobuf::DescriptorPool.generated_pool.lookup('protos.ChaincodeHeaderExtension').msgclass
  ChaincodeProposalPayload = Google::Protobuf::DescriptorPool.generated_pool.lookup('protos.ChaincodeProposalPayload').msgclass
  ChaincodeAction = Google::Protobuf::DescriptorPool.generated_pool.lookup('protos.ChaincodeAction').msgclass
end
