# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ledger/rwset/rwset.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "rwset.TxReadWriteSet" do
    optional :data_model, :enum, 1, "rwset.TxReadWriteSet.DataModel"
    repeated :ns_rwset, :message, 2, "rwset.NsReadWriteSet"
  end
  add_enum "rwset.TxReadWriteSet.DataModel" do
    value :KV, 0
  end
  add_message "rwset.NsReadWriteSet" do
    optional :namespace, :string, 1
    optional :rwset, :bytes, 2
    repeated :collection_hashed_rwset, :message, 3, "rwset.CollectionHashedReadWriteSet"
  end
  add_message "rwset.CollectionHashedReadWriteSet" do
    optional :collection_name, :string, 1
    optional :hashed_rwset, :bytes, 2
    optional :pvt_rwset_hash, :bytes, 3
  end
  add_message "rwset.TxPvtReadWriteSet" do
    optional :data_model, :enum, 1, "rwset.TxReadWriteSet.DataModel"
    repeated :ns_pvt_rwset, :message, 2, "rwset.NsPvtReadWriteSet"
  end
  add_message "rwset.NsPvtReadWriteSet" do
    optional :namespace, :string, 1
    repeated :collection_pvt_rwset, :message, 2, "rwset.CollectionPvtReadWriteSet"
  end
  add_message "rwset.CollectionPvtReadWriteSet" do
    optional :collection_name, :string, 1
    optional :rwset, :bytes, 2
  end
end

module Rwset
  TxReadWriteSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("rwset.TxReadWriteSet").msgclass
  TxReadWriteSet::DataModel = Google::Protobuf::DescriptorPool.generated_pool.lookup("rwset.TxReadWriteSet.DataModel").enummodule
  NsReadWriteSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("rwset.NsReadWriteSet").msgclass
  CollectionHashedReadWriteSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("rwset.CollectionHashedReadWriteSet").msgclass
  TxPvtReadWriteSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("rwset.TxPvtReadWriteSet").msgclass
  NsPvtReadWriteSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("rwset.NsPvtReadWriteSet").msgclass
  CollectionPvtReadWriteSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("rwset.CollectionPvtReadWriteSet").msgclass
end
