# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderer/etcdraft/configuration.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message 'etcdraft.Metadata' do
    repeated :consenters, :message, 1, 'etcdraft.Consenter'
  end
  add_message 'etcdraft.Consenter' do
    optional :host, :string, 1
    optional :port, :uint32, 2
    optional :client_tls_cert, :bytes, 3
    optional :server_tls_cert, :bytes, 4
  end
end

module Etcdraft
  Metadata = Google::Protobuf::DescriptorPool.generated_pool.lookup('etcdraft.Metadata').msgclass
  Consenter = Google::Protobuf::DescriptorPool.generated_pool.lookup('etcdraft.Consenter').msgclass
end
