# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ledger/rwset/kvrwset/kv_rwset.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "kvrwset.KVRWSet" do
    repeated :reads, :message, 1, "kvrwset.KVRead"
    repeated :range_queries_info, :message, 2, "kvrwset.RangeQueryInfo"
    repeated :writes, :message, 3, "kvrwset.KVWrite"
  end
  add_message "kvrwset.KVRead" do
    optional :key, :string, 1
    optional :version, :message, 2, "kvrwset.Version"
  end
  add_message "kvrwset.KVWrite" do
    optional :key, :string, 1
    optional :is_delete, :bool, 2
    optional :value, :bytes, 3
  end
  add_message "kvrwset.Version" do
    optional :block_num, :uint64, 1
    optional :tx_num, :uint64, 2
  end
  add_message "kvrwset.RangeQueryInfo" do
    optional :start_key, :string, 1
    optional :end_key, :string, 2
    optional :itr_exhausted, :bool, 3
    oneof :reads_info do
      optional :raw_reads, :message, 4, "kvrwset.QueryReads"
      optional :reads_merkle_hashes, :message, 5, "kvrwset.QueryReadsMerkleSummary"
    end
  end
  add_message "kvrwset.QueryReads" do
    repeated :kv_reads, :message, 1, "kvrwset.KVRead"
  end
  add_message "kvrwset.QueryReadsMerkleSummary" do
    optional :max_degree, :uint32, 1
    optional :max_level, :uint32, 2
    repeated :max_level_hashes, :bytes, 3
  end
end

module Kvrwset
  KVRWSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("kvrwset.KVRWSet").msgclass
  KVRead = Google::Protobuf::DescriptorPool.generated_pool.lookup("kvrwset.KVRead").msgclass
  KVWrite = Google::Protobuf::DescriptorPool.generated_pool.lookup("kvrwset.KVWrite").msgclass
  Version = Google::Protobuf::DescriptorPool.generated_pool.lookup("kvrwset.Version").msgclass
  RangeQueryInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("kvrwset.RangeQueryInfo").msgclass
  QueryReads = Google::Protobuf::DescriptorPool.generated_pool.lookup("kvrwset.QueryReads").msgclass
  QueryReadsMerkleSummary = Google::Protobuf::DescriptorPool.generated_pool.lookup("kvrwset.QueryReadsMerkleSummary").msgclass
end
