# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ledger/rwset/kvrwset/kv_rwset.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message 'kvrwset.KVRWSet' do
    repeated :reads, :message, 1, 'kvrwset.KVRead'
    repeated :range_queries_info, :message, 2, 'kvrwset.RangeQueryInfo'
    repeated :writes, :message, 3, 'kvrwset.KVWrite'
    repeated :metadata_writes, :message, 4, 'kvrwset.KVMetadataWrite'
  end
  add_message 'kvrwset.HashedRWSet' do
    repeated :hashed_reads, :message, 1, 'kvrwset.KVReadHash'
    repeated :hashed_writes, :message, 2, 'kvrwset.KVWriteHash'
    repeated :metadata_writes, :message, 3, 'kvrwset.KVMetadataWriteHash'
  end
  add_message 'kvrwset.KVRead' do
    optional :key, :string, 1
    optional :version, :message, 2, 'kvrwset.Version'
  end
  add_message 'kvrwset.KVWrite' do
    optional :key, :string, 1
    optional :is_delete, :bool, 2
    optional :value, :bytes, 3
  end
  add_message 'kvrwset.KVMetadataWrite' do
    optional :key, :string, 1
    repeated :entries, :message, 2, 'kvrwset.KVMetadataEntry'
  end
  add_message 'kvrwset.KVReadHash' do
    optional :key_hash, :bytes, 1
    optional :version, :message, 2, 'kvrwset.Version'
  end
  add_message 'kvrwset.KVWriteHash' do
    optional :key_hash, :bytes, 1
    optional :is_delete, :bool, 2
    optional :value_hash, :bytes, 3
  end
  add_message 'kvrwset.KVMetadataWriteHash' do
    optional :key_hash, :bytes, 1
    repeated :entries, :message, 2, 'kvrwset.KVMetadataEntry'
  end
  add_message 'kvrwset.KVMetadataEntry' do
    optional :name, :string, 1
    optional :value, :bytes, 2
  end
  add_message 'kvrwset.Version' do
    optional :block_num, :uint64, 1
    optional :tx_num, :uint64, 2
  end
  add_message 'kvrwset.RangeQueryInfo' do
    optional :start_key, :string, 1
    optional :end_key, :string, 2
    optional :itr_exhausted, :bool, 3
    oneof :reads_info do
      optional :raw_reads, :message, 4, 'kvrwset.QueryReads'
      optional :reads_merkle_hashes, :message, 5, 'kvrwset.QueryReadsMerkleSummary'
    end
  end
  add_message 'kvrwset.QueryReads' do
    repeated :kv_reads, :message, 1, 'kvrwset.KVRead'
  end
  add_message 'kvrwset.QueryReadsMerkleSummary' do
    optional :max_degree, :uint32, 1
    optional :max_level, :uint32, 2
    repeated :max_level_hashes, :bytes, 3
  end
end

module Kvrwset
  KVRWSet = Google::Protobuf::DescriptorPool.generated_pool.lookup('kvrwset.KVRWSet').msgclass
  HashedRWSet = Google::Protobuf::DescriptorPool.generated_pool.lookup('kvrwset.HashedRWSet').msgclass
  KVRead = Google::Protobuf::DescriptorPool.generated_pool.lookup('kvrwset.KVRead').msgclass
  KVWrite = Google::Protobuf::DescriptorPool.generated_pool.lookup('kvrwset.KVWrite').msgclass
  KVMetadataWrite = Google::Protobuf::DescriptorPool.generated_pool.lookup('kvrwset.KVMetadataWrite').msgclass
  KVReadHash = Google::Protobuf::DescriptorPool.generated_pool.lookup('kvrwset.KVReadHash').msgclass
  KVWriteHash = Google::Protobuf::DescriptorPool.generated_pool.lookup('kvrwset.KVWriteHash').msgclass
  KVMetadataWriteHash = Google::Protobuf::DescriptorPool.generated_pool.lookup('kvrwset.KVMetadataWriteHash').msgclass
  KVMetadataEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup('kvrwset.KVMetadataEntry').msgclass
  Version = Google::Protobuf::DescriptorPool.generated_pool.lookup('kvrwset.Version').msgclass
  RangeQueryInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup('kvrwset.RangeQueryInfo').msgclass
  QueryReads = Google::Protobuf::DescriptorPool.generated_pool.lookup('kvrwset.QueryReads').msgclass
  QueryReadsMerkleSummary = Google::Protobuf::DescriptorPool.generated_pool.lookup('kvrwset.QueryReadsMerkleSummary').msgclass
end
