# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transientstore/transientstore.proto

require 'google/protobuf'

require 'ledger/rwset/rwset_pb'
require 'common/collection_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "transientstore.TxPvtReadWriteSetWithConfigInfo" do
    optional :endorsed_at, :uint64, 1
    optional :pvt_rwset, :message, 2, "rwset.TxPvtReadWriteSet"
    map :collection_configs, :string, :message, 3, "common.CollectionConfigPackage"
  end
end

module Transientstore
  TxPvtReadWriteSetWithConfigInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("transientstore.TxPvtReadWriteSetWithConfigInfo").msgclass
end
