# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msp/identities.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "msp.SerializedIdentity" do
    optional :mspid, :string, 1
    optional :id_bytes, :bytes, 2
  end
end

module Msp
  SerializedIdentity = Google::Protobuf::DescriptorPool.generated_pool.lookup("msp.SerializedIdentity").msgclass
end
