# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: idemix/idemix.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ECP" do
    optional :x, :bytes, 1
    optional :y, :bytes, 2
  end
  add_message "ECP2" do
    optional :xa, :bytes, 1
    optional :xb, :bytes, 2
    optional :ya, :bytes, 3
    optional :yb, :bytes, 4
  end
  add_message "IssuerPublicKey" do
    repeated :attribute_names, :string, 1
    optional :h_sk, :message, 2, "ECP"
    optional :h_rand, :message, 3, "ECP"
    repeated :h_attrs, :message, 4, "ECP"
    optional :w, :message, 5, "ECP2"
    optional :bar_g1, :message, 6, "ECP"
    optional :bar_g2, :message, 7, "ECP"
    optional :proof_c, :bytes, 8
    optional :proof_s, :bytes, 9
    optional :hash, :bytes, 10
  end
  add_message "IssuerKey" do
    optional :isk, :bytes, 1
    optional :ipk, :message, 2, "IssuerPublicKey"
  end
  add_message "Credential" do
    optional :a, :message, 1, "ECP"
    optional :b, :message, 2, "ECP"
    optional :e, :bytes, 3
    optional :s, :bytes, 4
    repeated :attrs, :bytes, 5
  end
  add_message "CredRequest" do
    optional :nym, :message, 1, "ECP"
    optional :issuer_nonce, :bytes, 2
    optional :proof_c, :bytes, 3
    optional :proof_s, :bytes, 4
  end
  add_message "Signature" do
    optional :a_prime, :message, 1, "ECP"
    optional :a_bar, :message, 2, "ECP"
    optional :b_prime, :message, 3, "ECP"
    optional :proof_c, :bytes, 4
    optional :proof_s_sk, :bytes, 5
    optional :proof_s_e, :bytes, 6
    optional :proof_s_r2, :bytes, 7
    optional :proof_s_r3, :bytes, 8
    optional :proof_s_s_prime, :bytes, 9
    repeated :proof_s_attrs, :bytes, 10
    optional :nonce, :bytes, 11
    optional :nym, :message, 12, "ECP"
    optional :proof_s_r_nym, :bytes, 13
    optional :revocation_epoch_pk, :message, 14, "ECP2"
    optional :revocation_pk_sig, :bytes, 15
    optional :epoch, :int64, 16
    optional :non_revocation_proof, :message, 17, "NonRevocationProof"
  end
  add_message "NonRevocationProof" do
    optional :revocation_alg, :int32, 1
    optional :non_revocation_proof, :bytes, 2
  end
  add_message "NymSignature" do
    optional :proof_c, :bytes, 1
    optional :proof_s_sk, :bytes, 2
    optional :proof_s_r_nym, :bytes, 3
    optional :nonce, :bytes, 4
  end
  add_message "CredentialRevocationInformation" do
    optional :epoch, :int64, 1
    optional :epoch_pk, :message, 2, "ECP2"
    optional :epoch_pk_sig, :bytes, 3
    optional :revocation_alg, :int32, 4
    optional :revocation_data, :bytes, 5
  end
end

ECP = Google::Protobuf::DescriptorPool.generated_pool.lookup("ECP").msgclass
ECP2 = Google::Protobuf::DescriptorPool.generated_pool.lookup("ECP2").msgclass
IssuerPublicKey = Google::Protobuf::DescriptorPool.generated_pool.lookup("IssuerPublicKey").msgclass
IssuerKey = Google::Protobuf::DescriptorPool.generated_pool.lookup("IssuerKey").msgclass
Credential = Google::Protobuf::DescriptorPool.generated_pool.lookup("Credential").msgclass
CredRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("CredRequest").msgclass
Signature = Google::Protobuf::DescriptorPool.generated_pool.lookup("Signature").msgclass
NonRevocationProof = Google::Protobuf::DescriptorPool.generated_pool.lookup("NonRevocationProof").msgclass
NymSignature = Google::Protobuf::DescriptorPool.generated_pool.lookup("NymSignature").msgclass
CredentialRevocationInformation = Google::Protobuf::DescriptorPool.generated_pool.lookup("CredentialRevocationInformation").msgclass
