# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ledger/rwset/rwset.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "rwset.TxReadWriteSet" do
    optional :data_model, :enum, 1, "rwset.TxReadWriteSet.DataModel"
    repeated :ns_rwset, :message, 2, "rwset.NsReadWriteSet"
  end
  add_enum "rwset.TxReadWriteSet.DataModel" do
    value :KV, 0
  end
  add_message "rwset.NsReadWriteSet" do
    optional :namespace, :string, 1
    optional :rwset, :bytes, 2
  end
end

module Rwset
  TxReadWriteSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("rwset.TxReadWriteSet").msgclass
  TxReadWriteSet::DataModel = Google::Protobuf::DescriptorPool.generated_pool.lookup("rwset.TxReadWriteSet.DataModel").enummodule
  NsReadWriteSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("rwset.NsReadWriteSet").msgclass
end
