# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/peer.proto

require 'google/protobuf'

require 'peer/proposal_pb'
require 'peer/proposal_response_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protos.PeerID" do
    optional :name, :string, 1
  end
  add_message "protos.PeerEndpoint" do
    optional :id, :message, 1, "protos.PeerID"
    optional :address, :string, 2
  end
end

module Protos
  PeerID = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.PeerID").msgclass
  PeerEndpoint = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.PeerEndpoint").msgclass
end
