# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/common.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "common.LastConfig" do
    optional :index, :uint64, 1
  end
  add_message "common.Metadata" do
    optional :value, :bytes, 1
    repeated :signatures, :message, 2, "common.MetadataSignature"
  end
  add_message "common.MetadataSignature" do
    optional :signature_header, :bytes, 1
    optional :signature, :bytes, 2
  end
  add_message "common.Header" do
    optional :channel_header, :bytes, 1
    optional :signature_header, :bytes, 2
  end
  add_message "common.ChannelHeader" do
    optional :type, :int32, 1
    optional :version, :int32, 2
    optional :timestamp, :message, 3, "google.protobuf.Timestamp"
    optional :channel_id, :string, 4
    optional :tx_id, :string, 5
    optional :epoch, :uint64, 6
    optional :extension, :bytes, 7
  end
  add_message "common.SignatureHeader" do
    optional :creator, :bytes, 1
    optional :nonce, :bytes, 2
  end
  add_message "common.Payload" do
    optional :header, :message, 1, "common.Header"
    optional :data, :bytes, 2
  end
  add_message "common.Envelope" do
    optional :payload, :bytes, 1
    optional :signature, :bytes, 2
  end
  add_message "common.Block" do
    optional :header, :message, 1, "common.BlockHeader"
    optional :data, :message, 2, "common.BlockData"
    optional :metadata, :message, 3, "common.BlockMetadata"
  end
  add_message "common.BlockHeader" do
    optional :number, :uint64, 1
    optional :previous_hash, :bytes, 2
    optional :data_hash, :bytes, 3
  end
  add_message "common.BlockData" do
    repeated :data, :bytes, 1
  end
  add_message "common.BlockMetadata" do
    repeated :metadata, :bytes, 1
  end
  add_enum "common.Status" do
    value :UNKNOWN, 0
    value :SUCCESS, 200
    value :BAD_REQUEST, 400
    value :FORBIDDEN, 403
    value :NOT_FOUND, 404
    value :REQUEST_ENTITY_TOO_LARGE, 413
    value :INTERNAL_SERVER_ERROR, 500
    value :SERVICE_UNAVAILABLE, 503
  end
  add_enum "common.HeaderType" do
    value :MESSAGE, 0
    value :CONFIG, 1
    value :CONFIG_UPDATE, 2
    value :ENDORSER_TRANSACTION, 3
    value :ORDERER_TRANSACTION, 4
    value :DELIVER_SEEK_INFO, 5
    value :CHAINCODE_PACKAGE, 6
  end
  add_enum "common.BlockMetadataIndex" do
    value :SIGNATURES, 0
    value :LAST_CONFIG, 1
    value :TRANSACTIONS_FILTER, 2
    value :ORDERER, 3
  end
end

module Common
  LastConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.LastConfig").msgclass
  Metadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.Metadata").msgclass
  MetadataSignature = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.MetadataSignature").msgclass
  Header = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.Header").msgclass
  ChannelHeader = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.ChannelHeader").msgclass
  SignatureHeader = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.SignatureHeader").msgclass
  Payload = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.Payload").msgclass
  Envelope = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.Envelope").msgclass
  Block = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.Block").msgclass
  BlockHeader = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.BlockHeader").msgclass
  BlockData = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.BlockData").msgclass
  BlockMetadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.BlockMetadata").msgclass
  Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.Status").enummodule
  HeaderType = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.HeaderType").enummodule
  BlockMetadataIndex = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.BlockMetadataIndex").enummodule
end
