# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/configtx.proto

require 'google/protobuf'

require 'common/common_pb'
require 'common/policies_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "common.ConfigEnvelope" do
    optional :config, :message, 1, "common.Config"
    optional :last_update, :message, 2, "common.Envelope"
  end
  add_message "common.ConfigGroupSchema" do
    map :groups, :string, :message, 1, "common.ConfigGroupSchema"
    map :values, :string, :message, 2, "common.ConfigValueSchema"
    map :policies, :string, :message, 3, "common.ConfigPolicySchema"
  end
  add_message "common.ConfigValueSchema" do
  end
  add_message "common.ConfigPolicySchema" do
  end
  add_message "common.Config" do
    optional :sequence, :uint64, 1
    optional :channel_group, :message, 2, "common.ConfigGroup"
  end
  add_message "common.ConfigUpdateEnvelope" do
    optional :config_update, :bytes, 1
    repeated :signatures, :message, 2, "common.ConfigSignature"
  end
  add_message "common.ConfigUpdate" do
    optional :channel_id, :string, 1
    optional :read_set, :message, 2, "common.ConfigGroup"
    optional :write_set, :message, 3, "common.ConfigGroup"
  end
  add_message "common.ConfigGroup" do
    optional :version, :uint64, 1
    map :groups, :string, :message, 2, "common.ConfigGroup"
    map :values, :string, :message, 3, "common.ConfigValue"
    map :policies, :string, :message, 4, "common.ConfigPolicy"
    optional :mod_policy, :string, 5
  end
  add_message "common.ConfigValue" do
    optional :version, :uint64, 1
    optional :value, :bytes, 2
    optional :mod_policy, :string, 3
  end
  add_message "common.ConfigPolicy" do
    optional :version, :uint64, 1
    optional :policy, :message, 2, "common.Policy"
    optional :mod_policy, :string, 3
  end
  add_message "common.ConfigSignature" do
    optional :signature_header, :bytes, 1
    optional :signature, :bytes, 2
  end
end

module Common
  ConfigEnvelope = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.ConfigEnvelope").msgclass
  ConfigGroupSchema = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.ConfigGroupSchema").msgclass
  ConfigValueSchema = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.ConfigValueSchema").msgclass
  ConfigPolicySchema = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.ConfigPolicySchema").msgclass
  Config = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.Config").msgclass
  ConfigUpdateEnvelope = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.ConfigUpdateEnvelope").msgclass
  ConfigUpdate = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.ConfigUpdate").msgclass
  ConfigGroup = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.ConfigGroup").msgclass
  ConfigValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.ConfigValue").msgclass
  ConfigPolicy = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.ConfigPolicy").msgclass
  ConfigSignature = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.ConfigSignature").msgclass
end
