# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/ledger.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "common.BlockchainInfo" do
    optional :height, :uint64, 1
    optional :currentBlockHash, :bytes, 2
    optional :previousBlockHash, :bytes, 3
  end
end

module Common
  BlockchainInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("common.BlockchainInfo").msgclass
end
