# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/admin.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protos.ServerStatus" do
    optional :status, :enum, 1, "protos.ServerStatus.StatusCode"
  end
  add_enum "protos.ServerStatus.StatusCode" do
    value :UNDEFINED, 0
    value :STARTED, 1
    value :STOPPED, 2
    value :PAUSED, 3
    value :ERROR, 4
    value :UNKNOWN, 5
  end
  add_message "protos.LogLevelRequest" do
    optional :log_module, :string, 1
    optional :log_level, :string, 2
  end
  add_message "protos.LogLevelResponse" do
    optional :log_module, :string, 1
    optional :log_level, :string, 2
  end
end

module Protos
  ServerStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.ServerStatus").msgclass
  ServerStatus::StatusCode = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.ServerStatus.StatusCode").enummodule
  LogLevelRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.LogLevelRequest").msgclass
  LogLevelResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.LogLevelResponse").msgclass
end
