# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: peer/chaincode_shim.proto for package 'protos'
# Original file comments:
#
# Copyright IBM Corp. 2017 All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require 'peer/chaincode_shim_pb'

module Protos
  module ChaincodeSupport
    # Interface that provides support to chaincode execution. ChaincodeContext
    # provides the context necessary for the server to respond appropriately.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'protos.ChaincodeSupport'

      rpc :Register, stream(ChaincodeMessage), stream(ChaincodeMessage)
    end

    Stub = Service.rpc_stub_class
  end
end
