# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/configuration.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protos.AnchorPeers" do
    repeated :anchor_peers, :message, 1, "protos.AnchorPeer"
  end
  add_message "protos.AnchorPeer" do
    optional :host, :string, 1
    optional :port, :int32, 2
  end
end

module Protos
  AnchorPeers = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.AnchorPeers").msgclass
  AnchorPeer = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.AnchorPeer").msgclass
end
