# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/events.proto

require 'google/protobuf'

require 'common/common_pb'
require 'peer/chaincode_event_pb'
require 'peer/transaction_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protos.ChaincodeReg" do
    optional :chaincode_id, :string, 1
    optional :event_name, :string, 2
  end
  add_message "protos.Interest" do
    optional :event_type, :enum, 1, "protos.EventType"
    optional :chainID, :string, 3
    oneof :RegInfo do
      optional :chaincode_reg_info, :message, 2, "protos.ChaincodeReg"
    end
  end
  add_message "protos.Register" do
    repeated :events, :message, 1, "protos.Interest"
  end
  add_message "protos.Rejection" do
    optional :tx, :message, 1, "protos.Transaction"
    optional :error_msg, :string, 2
  end
  add_message "protos.Unregister" do
    repeated :events, :message, 1, "protos.Interest"
  end
  add_message "protos.SignedEvent" do
    optional :signature, :bytes, 1
    optional :eventBytes, :bytes, 2
  end
  add_message "protos.Event" do
    optional :creator, :bytes, 6
    oneof :Event do
      optional :register, :message, 1, "protos.Register"
      optional :block, :message, 2, "common.Block"
      optional :chaincode_event, :message, 3, "protos.ChaincodeEvent"
      optional :rejection, :message, 4, "protos.Rejection"
      optional :unregister, :message, 5, "protos.Unregister"
    end
  end
  add_enum "protos.EventType" do
    value :REGISTER, 0
    value :BLOCK, 1
    value :CHAINCODE, 2
    value :REJECTION, 3
  end
end

module Protos
  ChaincodeReg = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.ChaincodeReg").msgclass
  Interest = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.Interest").msgclass
  Register = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.Register").msgclass
  Rejection = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.Rejection").msgclass
  Unregister = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.Unregister").msgclass
  SignedEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.SignedEvent").msgclass
  Event = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.Event").msgclass
  EventType = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.EventType").enummodule
end
