# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/signed_cc_dep_spec.proto

require 'google/protobuf'

require 'peer/proposal_response_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protos.SignedChaincodeDeploymentSpec" do
    optional :chaincode_deployment_spec, :bytes, 1
    optional :instantiation_policy, :bytes, 2
    repeated :owner_endorsements, :message, 3, "protos.Endorsement"
  end
end

module Protos
  SignedChaincodeDeploymentSpec = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.SignedChaincodeDeploymentSpec").msgclass
end
